"""initial schema

Revision ID: 1b78bf89715f
Revises: 
Create Date: 2026-09-15 16:58:03.595699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b78bf89715f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_kind', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('subject_member_id', sa.String(length=36), nullable=True),
    sa.Column('object_ids_json', sa.JSON(), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tz_default', sa.String(length=64), nullable=False),
    sa.Column('prompt_local_time', sa.String(length=5), nullable=False),
    sa.Column('cutoff_local_time', sa.String(length=5), nullable=False),
    sa.Column('workdays', sa.String(length=20), nullable=False),
    sa.Column('github_repo', sa.String(length=200), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('member',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('tz', sa.String(length=64), nullable=False),
    sa.Column('source_keys', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standup_cycle',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('opens_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cutoff_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'local_date', name='uq_cycle_team_date')
    )
    op.create_table('digest',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('summarizer_name', sa.String(length=64), nullable=False),
    sa.Column('summarizer_version', sa.String(length=32), nullable=False),
    sa.Column('validator_report_json', sa.JSON(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('withheld_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['standup_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_ids_json', sa.JSON(), nullable=False),
    sa.Column('permalink', sa.String(length=1000), nullable=True),
    sa.Column('permalink_reason', sa.String(length=200), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['standup_cycle.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('digest_claim',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('digest_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('member_name', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('citations_json', sa.JSON(), nullable=False),
    sa.Column('extractive', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digest.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('update_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=False),
    sa.Column('span_end', sa.Integer(), nullable=False),
    sa.Column('normalized_key', sa.String(length=500), nullable=False),
    sa.Column('entity_refs', sa.JSON(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['update_id'], ['update.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_item')
    op.drop_table('digest_claim')
    op.drop_table('update')
    op.drop_table('digest')
    op.drop_table('standup_cycle')
    op.drop_table('member')
    op.drop_table('team')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
